// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uHdm286nsA1LVw4Z68JgXh
// Component: izGfKZi6KdYi
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import CardPorto from "../../CardPorto"; // plasmic-import: WGpzMwoiUz/component

import { useScreenVariants as useScreenVariantseldZv02Iw4Xh } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: Eld-ZV02Iw4XH/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_pujaarsana.module.css"; // plasmic-import: uHdm286nsA1LVw4Z68JgXh/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: izGfKZi6KdYi/css

import LocationSvgrepoComsvgIcon from "./icons/PlasmicIcon__LocationSvgrepoComsvg"; // plasmic-import: KbksUeDaO0/icon

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  section?: p.Flex<"section">;
  h1?: p.Flex<"h1">;
  svg?: p.Flex<"svg">;
};

export interface DefaultHomepageProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantseldZv02Iw4Xh()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <p.Stack
            as={"section"}
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            hasGap={true}
            className={classNames(projectcss.all, sty.section)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__tpAu)}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__ozVW)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"auto" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/pujaarsana/images/image.png",
                  fullWidth: 160,
                  fullHeight: 160,
                  aspectRatio: undefined
                }}
              />

              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__pbrfl)}
                >
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"Puja Arsana Sujana"}
                  </h1>

                  {true ? (
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___961JE
                      )}
                    >
                      <LocationSvgrepoComsvgIcon
                        data-plasmic-name={"svg"}
                        data-plasmic-override={overrides.svg}
                        className={classNames(projectcss.all, sty.svg)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___6MkIa
                        )}
                      >
                        {"Gianyar, Bali, Indonesia"}
                      </div>
                    </p.Stack>
                  ) : null}
                  {true ? (
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__e2Btb)}
                    >
                      {true ? (
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__pFtU
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ohlz
                            )}
                          >
                            {"Product Management"}
                          </div>
                        </p.Stack>
                      ) : null}
                      {true ? (
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__vfW2
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ul9Dc
                            )}
                          >
                            {"Product Designer"}
                          </div>
                        </p.Stack>
                      ) : null}
                      {true ? (
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__uh7NU
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__knZn3
                            )}
                          >
                            {"UI/UX Designer"}
                          </div>
                        </p.Stack>
                      ) : null}
                      {true ? (
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__jFh7
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___4Pgwg
                            )}
                          >
                            {"Web3"}
                          </div>
                        </p.Stack>
                      ) : null}
                      {true ? (
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__nnCT
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___9EY6
                            )}
                          >
                            {"Blockchain"}
                          </div>
                        </p.Stack>
                      ) : null}
                    </p.Stack>
                  ) : null}
                </p.Stack>
              ) : null}
            </p.Stack>

            <div className={classNames(projectcss.all, sty.freeBox__tNmk4)}>
              <div className={classNames(projectcss.all, sty.freeBox__xwYdw)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__l2GZi)}
                >
                  {true ? (
                    <CardPorto
                      className={classNames(
                        "__wab_instance",
                        sty.cardPorto__a9WxC
                      )}
                      slot={"NFT Coupon"}
                      slot2={
                        "Product strategy development,  requirement gathering, UI/UX design, end to end flow, translated product strategy into detailed requirements and delivered a web3 NFT coupon marketplace"
                      }
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___4MFmT)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/pujaarsana/images/port14Png.png",
                          fullWidth: 1024,
                          fullHeight: 768,
                          aspectRatio: undefined
                        }}
                      />
                    </CardPorto>
                  ) : null}
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__wu7LZ)}
                >
                  {true ? (
                    <CardPorto
                      className={classNames(
                        "__wab_instance",
                        sty.cardPorto__hg8Kl
                      )}
                      slot={"NFT Ticketing"}
                      slot2={
                        "End-to-end product flow, UI/UX design, and delivering seamless user experiences focus on web3 ticketing systems."
                      }
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__gi9P4)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/pujaarsana/images/port13Png.png",
                          fullWidth: 1024,
                          fullHeight: 768,
                          aspectRatio: undefined
                        }}
                      />
                    </CardPorto>
                  ) : null}
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___2JjnS)}
                >
                  {true ? (
                    <CardPorto
                      className={classNames(
                        "__wab_instance",
                        sty.cardPorto__v8GLm
                      )}
                      slot={"Ramerame.co.id"}
                      slot2={
                        "End-to-end product flow, UI/UX design, and delivering seamless user experiences for Ramerame.co.id"
                      }
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___4Hdkv)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/pujaarsana/images/port15Png.png",
                          fullWidth: 1024,
                          fullHeight: 768,
                          aspectRatio: undefined
                        }}
                      />
                    </CardPorto>
                  ) : null}
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__gxZhN)}
                >
                  {true ? (
                    <CardPorto
                      className={classNames(
                        "__wab_instance",
                        sty.cardPorto__z4Rz0
                      )}
                      slot={"Gemolz Fresh Juice"}
                      slot2={"UI/UX Design for Gemolz fresh juice apps"}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__h9V6L)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/pujaarsana/images/port16Png.png",
                          fullWidth: 1024,
                          fullHeight: 768,
                          aspectRatio: undefined
                        }}
                      />
                    </CardPorto>
                  ) : null}
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__qAeoI)}
                >
                  {true ? (
                    <CardPorto
                      className={classNames(
                        "__wab_instance",
                        sty.cardPorto__eyeP
                      )}
                      slot={"Thealphalets"}
                      slot2={"UI/UX Design for Online invoice and ledger"}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__k68R)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/pujaarsana/images/port12Png.png",
                          fullWidth: 1024,
                          fullHeight: 768,
                          aspectRatio: undefined
                        }}
                      />
                    </CardPorto>
                  ) : null}
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__peo0G)}
                >
                  {true ? (
                    <CardPorto
                      className={classNames(
                        "__wab_instance",
                        sty.cardPorto___6QYjR
                      )}
                      slot={"Astungkara.co"}
                      slot2={"UI/UX Design for Gemolz fresh juice apps"}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__mmdar)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/pujaarsana/images/port11Png.png",
                          fullWidth: 1024,
                          fullHeight: 768,
                          aspectRatio: undefined
                        }}
                      />
                    </CardPorto>
                  ) : null}
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__mHfdP)}
                >
                  {true ? (
                    <CardPorto
                      className={classNames(
                        "__wab_instance",
                        sty.cardPorto___4I1B4
                      )}
                      slot={"Astungkara.co"}
                      slot2={"UI/UX Design for Gemolz fresh juice apps"}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__x90Sk)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/pujaarsana/images/port10Png.png",
                          fullWidth: 1024,
                          fullHeight: 768,
                          aspectRatio: undefined
                        }}
                      />
                    </CardPorto>
                  ) : null}
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__p5MfZ)}
                >
                  {true ? (
                    <CardPorto
                      className={classNames(
                        "__wab_instance",
                        sty.cardPorto__hj0Ux
                      )}
                      slot={"Quiz Apps"}
                      slot2={"UI/UX Design for Gemolz fresh juice apps"}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__mNz69)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/pujaarsana/images/portpng.png",
                          fullWidth: 1024,
                          fullHeight: 768,
                          aspectRatio: undefined
                        }}
                      />
                    </CardPorto>
                  ) : null}
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__gcE2L)}
                >
                  {true ? (
                    <CardPorto
                      className={classNames(
                        "__wab_instance",
                        sty.cardPorto___3CEEq
                      )}
                      slot={"Bank Discount Apps"}
                      slot2={"UI/UX Design for Gemolz fresh juice apps"}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__axjcN)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/pujaarsana/images/port8Png.png",
                          fullWidth: 1024,
                          fullHeight: 768,
                          aspectRatio: undefined
                        }}
                      />
                    </CardPorto>
                  ) : null}
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__nXv6A)}
                >
                  {true ? (
                    <CardPorto
                      className={classNames(
                        "__wab_instance",
                        sty.cardPorto__iIHoM
                      )}
                      slot={"FMCG Company"}
                      slot2={"UI/UX Design for Gemolz fresh juice apps"}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__atFgP)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/pujaarsana/images/port7Png.png",
                          fullWidth: 1024,
                          fullHeight: 768,
                          aspectRatio: undefined
                        }}
                      />
                    </CardPorto>
                  ) : null}
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__vitNo)}
                >
                  {true ? (
                    <CardPorto
                      className={classNames(
                        "__wab_instance",
                        sty.cardPorto__sQlAa
                      )}
                      slot={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__nyJwu
                          )}
                        >
                          {"Tourism Apps"}
                        </div>
                      }
                      slot2={"UI/UX Design for Gemolz fresh juice apps"}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__zOJtQ)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/pujaarsana/images/port6Png.png",
                          fullWidth: 1024,
                          fullHeight: 768,
                          aspectRatio: undefined
                        }}
                      />
                    </CardPorto>
                  ) : null}
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__g2YaX)}
                >
                  {true ? (
                    <CardPorto
                      className={classNames(
                        "__wab_instance",
                        sty.cardPorto__hmV6Y
                      )}
                      slot={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__gXmEn
                          )}
                        >
                          {"Sales Dashboard Apps"}
                        </div>
                      }
                      slot2={"UI/UX Design for Gemolz fresh juice apps"}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__ukZsK)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/pujaarsana/images/port9Png.png",
                          fullWidth: 1024,
                          fullHeight: 768,
                          aspectRatio: undefined
                        }}
                      />
                    </CardPorto>
                  ) : null}
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___6N5BY)}
                >
                  {true ? (
                    <CardPorto
                      className={classNames(
                        "__wab_instance",
                        sty.cardPorto__uxfh5
                      )}
                      slot={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ddNg6
                          )}
                        >
                          {"Human Resource Development Apps"}
                        </div>
                      }
                      slot2={"UI/UX Design for Gemolz fresh juice apps"}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__a7BQ4)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/pujaarsana/images/port5Png.png",
                          fullWidth: 1024,
                          fullHeight: 768,
                          aspectRatio: undefined
                        }}
                      />
                    </CardPorto>
                  ) : null}
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__errRg)}
                >
                  {true ? (
                    <CardPorto
                      className={classNames(
                        "__wab_instance",
                        sty.cardPorto___3Jb85
                      )}
                      slot={"Tax consulting Apps"}
                      slot2={
                        "UI/UX Design for tax consulting application from Ayotax"
                      }
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__oiGdK)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/pujaarsana/images/port4Png.png",
                          fullWidth: 1024,
                          fullHeight: 768,
                          aspectRatio: undefined
                        }}
                      />
                    </CardPorto>
                  ) : null}
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__xwy0U)}
                >
                  {true ? (
                    <CardPorto
                      className={classNames(
                        "__wab_instance",
                        sty.cardPorto__p4E77
                      )}
                      slot={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___0CaQ5
                          )}
                        >
                          {"Cash Collection Apps"}
                        </div>
                      }
                      slot2={"UI/UX Design for Cash collection from Stor.id"}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__rWb1)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/pujaarsana/images/port3Png.png",
                          fullWidth: 1024,
                          fullHeight: 768,
                          aspectRatio: undefined
                        }}
                      />
                    </CardPorto>
                  ) : null}
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___3G7Ht)}
                >
                  {true ? (
                    <CardPorto
                      className={classNames(
                        "__wab_instance",
                        sty.cardPorto__l4WDu
                      )}
                      slot={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___7VYrJ
                          )}
                        >
                          {"Cash Collection Apps"}
                        </div>
                      }
                      slot2={
                        "UX/UI Design for buying and selling  bankruptcy assets from asset Curator Boedel.id"
                      }
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__jNnS3)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/pujaarsana/images/port2Png.png",
                          fullWidth: 1024,
                          fullHeight: 768,
                          aspectRatio: undefined
                        }}
                      />
                    </CardPorto>
                  ) : null}
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__sFmGj)}
                >
                  {true ? (
                    <CardPorto
                      className={classNames(
                        "__wab_instance",
                        sty.cardPorto__uZhcn
                      )}
                      slot={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__jAcTu
                          )}
                        >
                          {"Boedel Apps"}
                        </div>
                      }
                      slot2={
                        "UX/UI Design for buying and selling  bankruptcy assets from asset Curator Boedel.id"
                      }
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__sFzIy)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/pujaarsana/images/port2Png.png",
                          fullWidth: 1024,
                          fullHeight: 768,
                          aspectRatio: undefined
                        }}
                      />
                    </CardPorto>
                  ) : null}
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__fvJf0)}
                >
                  {true ? (
                    <CardPorto
                      className={classNames(
                        "__wab_instance",
                        sty.cardPorto__a8Xpe
                      )}
                      slot={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__b2R5
                          )}
                        >
                          {"Robocall"}
                        </div>
                      }
                      slot2={
                        "UI/UX Design for an Online campaign platform combined with artificial intelligence technology to automatically make calls to numbers that have been determined by the robot\n"
                      }
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__jWr1G)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/pujaarsana/images/port1Png.png",
                          fullWidth: 1024,
                          fullHeight: 768,
                          aspectRatio: undefined
                        }}
                      />
                    </CardPorto>
                  ) : null}
                </p.Stack>
              </div>
            </div>
          </p.Stack>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "section", "h1", "svg"],
  section: ["section", "h1", "svg"],
  h1: ["h1"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  section: "section";
  h1: "h1";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    section: makeNodeComponent("section"),
    h1: makeNodeComponent("h1"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
